server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://39.97.233.189:3306/whodo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.97.233.189
    port: 6379
    password: vae766567
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0


mybatis-plus:
  type-aliases-package: com.nopava.whodo.entity
  mapper-locations: classpath:mapping/*Mapper.xml
mybatis:
  type-aliases-package: com.nopava.whodo.entity
  mapper-locations: classpath:mapping/*Mapper.xml
